### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by anirudhagarwal365** [edgardmessias/vscode.override-mark#51]
This extension does not seem to work at all.

VS Code version - (version 1.48)

Project language - TypeScript
Project type - React Native

**Comment by anirudhagarwal365** [comment]
@edgardmessias This is a much needed feature coming in from an IDE. Please let me know if you need any inputs from my end.

**Comment by edgardmessias** [comment]
Hi @anirudhagarwal365 , I will work on it today

**Comment by anirudhagarwal365** [comment]
Hi @edgardmessias . Were you able to successfully replicate the issue?

**Comment by edgardmessias** [comment]
I made some tests here, but I couldn't replicate the issue.

Could you give some file for test?

**Comment by anirudhagarwal365** [comment]
Hi @edgardmessias , to help you reproduce the issue, I forked an existing github project - https://github.com/anirudhagarwal365/ReactNative-Redux-TypeScript-Boilerplate/tree/master

Here I have created a file called CustomButton.tsx. Here I am trying to override the render function of Button class(defined in Button.tsx) and somehow the override indicator does not show up in CustomButton.tsx.
