### ISSUE TITLE
Feature: Language addition extensibility

### ISSUE THREAD

**Issue by TheBrenny** [edgardmessias/vscode.override-mark#60]
Likely a long-shot of a feature suggestion, but it would be awesome to add language extensibility so other languages like Java, Python and PHP can be implemented.

I would see this working as having an exposed API from this extension with a new extension "depending" on this one.

Maybe this is already implemented, but I haven't seen anything (let alone understood how the code works). :(

Thoughts?

**Comment by edgardmessias** [comment]
Yes, I did it, look this line: https://github.com/edgardmessias/vscode.override-mark/blob/f8716a0be9ac76f92103f8e45d482d21e8e91bf1/src/extension.ts#L55

You must implement the [Provider](https://github.com/edgardmessias/vscode.override-mark/blob/f8716a0be9ac76f92103f8e45d482d21e8e91bf1/src/overrider-mark.ts#L14) interface and use a code like below:

```ts
let ext = extensions.getExtension('EdgardMessias.override-mark');
let api = ext.exports;
api.addProvider(<your provider here>)

```
